
CREATE DATABASE IF NOT EXISTS blog;

USE blog;

CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR NOT NULL,
    username VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS post (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR UNIQUE NOT NULL,
    user_id INT NOT NULL,
    title VARCHAR NOT NULL,
    content VARCHAR NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    CONSTRAINT FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS comment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR UNIQUE NOT NULL,
    user_id INT NOT NULL,
    post_id INT NOT NULL,
    content VARCAR NOT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP() NOT NULL
    CONSTRAINT FOREIGN KEY (user_id) REFERENCES user(id)
    CONSTRAINT FOREIGN KEY (post_id) REFERENCES post(id)
);
